# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sc-ansi}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin MacKenzie IV"]
  s.date = %q{2010-07-23}
  s.description = %q{Handles every aspect (that I could think of) of dealing with ANSI escape sequences.}
  s.email = %q{sinisterchipmunk@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/ansi.rb",
     "lib/ansi/code.rb",
     "lib/ansi/color.rb",
     "lib/ansi/cursor.rb",
     "lib/ansi/display.rb",
     "lib/ansi/match.rb",
     "lib/ansi/vt100.rb",
     "lib/core_ext/object.rb",
     "lib/core_ext/string.rb",
     "lib/sc-ansi.rb",
     "spec/lib/ansi/color_spec.rb",
     "spec/lib/ansi/cursor_spec.rb",
     "spec/lib/ansi/display_spec.rb",
     "spec/lib/ansi/match_spec.rb",
     "spec/lib/ansi_spec.rb",
     "spec/lib/core_ext/object_spec.rb",
     "spec/lib/core_ext/string_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/sinisterchipmunk/sc-ansi}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Handles every aspect (that I could think of) of dealing with ANSI escape sequences.}
  s.test_files = [
    "spec/lib/ansi/color_spec.rb",
     "spec/lib/ansi/cursor_spec.rb",
     "spec/lib/ansi/display_spec.rb",
     "spec/lib/ansi/match_spec.rb",
     "spec/lib/ansi_spec.rb",
     "spec/lib/core_ext/object_spec.rb",
     "spec/lib/core_ext/string_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sc-core-ext>, [">= 1.2.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<sc-core-ext>, [">= 1.2.1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<sc-core-ext>, [">= 1.2.1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

